package bankingsystem;

import com.formdev.flatlaf.FlatDarkLaf;
import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author enesi
 */
public class GUI_Start extends javax.swing.JFrame {

    /**
     * Creates new form GUI_Start
     */
    public GUI_Start() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(70, 73, 75)); // RGB renk kodu

            
        jLabel4.setForeground(new java.awt.Color(187, 187, 187));
        j_firstName.setForeground(new java.awt.Color(187, 187, 187));  // Yazı rengi: RGB(187, 187, 187)
        j_firstName.setBackground(new java.awt.Color(70, 73, 75));  // Arka plan rengi: RGB(140, 140, 140)

        j_lastName.setForeground(new java.awt.Color(187, 187, 187));  // Yazı rengi: RGB(187, 187, 187)
        j_lastName.setBackground(new java.awt.Color(70, 73, 75));  // Arka plan rengi: RGB(140, 140, 140)

        j_TCID.setForeground(new java.awt.Color(187, 187, 187));  // Yazı rengi: RGB(187, 187, 187)
        j_TCID.setBackground(new java.awt.Color(70, 73, 75));  // Arka plan rengi: RGB(140, 140, 140)
        jLabel5.setForeground(new java.awt.Color(187, 187, 187));
    }
    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegisterPanel = new javax.swing.JPanel();
        j_firstName = new javax.swing.JTextField();
        j_lastName = new javax.swing.JTextField();
        j_TCID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        button_SignIn = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        button_LogIn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(75, 75, 75));

        RegisterPanel.setBackground(new java.awt.Color(40, 40, 40));

        j_firstName.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        j_firstName.setText("First Name...");
        j_firstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_firstNameActionPerformed(evt);
            }
        });

        j_lastName.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        j_lastName.setText("Last Name...");

        j_TCID.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        j_TCID.setText("TCID/SSN...");

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel4.setText("Welcome to SBTU Network");

        button_SignIn.setBackground(new java.awt.Color(255, 158, 0));
        button_SignIn.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        button_SignIn.setForeground(new java.awt.Color(0, 0, 0));
        button_SignIn.setText("Register");
        button_SignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_SignInActionPerformed(evt);
            }
        });

        logo.setIcon(new javax.swing.ImageIcon("C:\\Users\\enesi\\Desktop\\Module Project\\Banking System Simulation\\assets\\sbtu-icon_2.png")); // NOI18N

        button_LogIn.setBackground(new java.awt.Color(255, 158, 0));
        button_LogIn.setFont(new java.awt.Font("Tw Cen MT", 0, 10)); // NOI18N
        button_LogIn.setForeground(new java.awt.Color(0, 0, 0));
        button_LogIn.setText("Login");
        button_LogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_LogInActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel5.setText("Already have an account?");

        javax.swing.GroupLayout RegisterPanelLayout = new javax.swing.GroupLayout(RegisterPanel);
        RegisterPanel.setLayout(RegisterPanelLayout);
        RegisterPanelLayout.setHorizontalGroup(
            RegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterPanelLayout.createSequentialGroup()
                .addGroup(RegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(RegisterPanelLayout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(jLabel4)
                        .addGap(1, 1, 1))
                    .addGroup(RegisterPanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(logo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(RegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegisterPanelLayout.createSequentialGroup()
                                .addComponent(button_SignIn)
                                .addGap(71, 71, 71))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(j_TCID, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(RegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(j_firstName, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(j_lastName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(RegisterPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(button_LogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        RegisterPanelLayout.setVerticalGroup(
            RegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegisterPanelLayout.createSequentialGroup()
                        .addGap(0, 70, Short.MAX_VALUE)
                        .addComponent(j_firstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(j_lastName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(j_TCID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(button_SignIn))
                    .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addGroup(RegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_LogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(54, 54, 54))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RegisterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RegisterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button_LogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_LogInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_LogInActionPerformed

    private void button_SignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_SignInActionPerformed
        String firstName = j_firstName.getText();
        String lastName = j_lastName.getText();
        String TCID = j_TCID.getText();

        Customer customer = new Customer(firstName,lastName,TCID);
        JOptionPane.showMessageDialog(null, "Registered Succesfully.");
    }//GEN-LAST:event_button_SignInActionPerformed

    private void j_firstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_firstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j_firstNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatDarkLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Start().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel RegisterPanel;
    private javax.swing.JButton button_LogIn;
    private javax.swing.JButton button_SignIn;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField j_TCID;
    private javax.swing.JTextField j_firstName;
    private javax.swing.JTextField j_lastName;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
