/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package bankingsystem;

import java.awt.GridLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;

/**
 *
 * @author enesi
 */
public class GUI_AccountSelection extends javax.swing.JPanel {
    
    
    
     private void showAccountActionsScreen(CheckingAccount account){
          GUI_AccountPanel accountPanel = new GUI_AccountPanel(
            account.accountType,
            account.getHolderName(),
            account.getBalance(),
            account.getIBAN()
    );
           jPanel1.removeAll();  // Mevcut içerikleri temizle
           jPanel1.add(accountPanel);  // Yeni paneli ekle
           jPanel1.revalidate();  // Yeniden düzenlemeyi yap
           jPanel1.repaint();  // Yeniden çizim yap
         
     }
    public void showAccountSelectionScreen(Customer customer) {
    // Paneli yeniden ayarla
    jPanel1.setLayout(new GridLayout(customer.accounts.size() + 2, 1, 10, 10));

    // Başlık etiketi
    JLabel titleLabel = new JLabel("Select an Account to Perform Actions:", SwingConstants.CENTER);
    jPanel1.add(titleLabel);

    // Hesap butonlarını ekle
    for (int i = 0; i < customer.accounts.size(); i++) {
        CheckingAccount account = customer.accounts.get(i);
        JButton accountButton = new JButton(account.accountType + " | " + account.getIBAN());
        int index = i; // Seçilen butonun index'ini kaydet
        accountButton.addActionListener(e -> showAccountActionsScreen(customer.accounts.get(index)));
        jPanel1.add(accountButton);
    }

    // Çıkış butonu ekle
    JButton exitButton = new JButton("Exit");
    exitButton.addActionListener(e -> System.exit(0));
    jPanel1.add(exitButton);
}

    public GUI_AccountSelection(Customer customer) {
        initComponents();
        showAccountSelectionScreen(customer);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setMaximumSize(new java.awt.Dimension(700, 540));
        setMinimumSize(new java.awt.Dimension(700, 540));
        setPreferredSize(new java.awt.Dimension(700, 540));

        jPanel1.setBackground(new java.awt.Color(30, 30, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
