/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package bankingsystem;

/**
 *
 * @author enesi
 */
public class GUI_AccountPanel extends javax.swing.JPanel {

        String accountType;
        String fullName;
        double balance;
        String IBAN;
    public GUI_AccountPanel(String accountType, String fullName, double balance, String IBAN) {
        initComponents();
        this.accountType = accountType;
        this.fullName = fullName;
        this.balance = balance;
        this.IBAN = IBAN;
        
      jaccountType.setText(accountType);
      jfullName.setText(fullName);
      jbalance.setText("<html><span style='color:#cc6600;'>BALANCE: </span>$" + this.balance + "</html>");
      jIBAN.setText(IBAN);
        
    }

    public GUI_AccountPanel() {
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jupperPane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jaccountType = new javax.swing.JLabel();
        jfullName = new javax.swing.JLabel();
        jIBAN = new javax.swing.JLabel();
        jcopyIBAN = new javax.swing.JButton();
        jdeposit = new javax.swing.JButton();
        jwithdraw = new javax.swing.JButton();
        jbalance = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setPreferredSize(new java.awt.Dimension(700, 540));

        jupperPane.setBackground(new java.awt.Color(30, 30, 30));
        jupperPane.setMaximumSize(new java.awt.Dimension(700, 540));
        jupperPane.setMinimumSize(new java.awt.Dimension(700, 540));
        jupperPane.setPreferredSize(new java.awt.Dimension(700, 540));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\enesi\\Desktop\\Module Project\\Banking System Simulation\\src\\smolusericon.png")); // NOI18N

        jaccountType.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jaccountType.setForeground(new java.awt.Color(253, 253, 253));
        jaccountType.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jaccountType.setText("Checking Account");
        jaccountType.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jfullName.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jfullName.setForeground(new java.awt.Color(253, 253, 253));
        jfullName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jfullName.setText("Lorem Ipsum");

        jIBAN.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jIBAN.setText("TR50 0001 5000 3200 4258 5862");

        jcopyIBAN.setBackground(new java.awt.Color(60, 63, 65));
        jcopyIBAN.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jcopyIBAN.setText("Copy IBAN");
        jcopyIBAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcopyIBANActionPerformed(evt);
            }
        });

        jdeposit.setBackground(new java.awt.Color(204, 102, 0));
        jdeposit.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jdeposit.setForeground(new java.awt.Color(253, 253, 253));
        jdeposit.setText("Deposit");

        jwithdraw.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jwithdraw.setText("Withdraw");

        jbalance.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jbalance.setForeground(new java.awt.Color(253, 253, 253));
        jbalance.setText("<html><span style='color:#cc6600;'>BALANCE: </span>$5236.21<html>");

        javax.swing.GroupLayout jupperPaneLayout = new javax.swing.GroupLayout(jupperPane);
        jupperPane.setLayout(jupperPaneLayout);
        jupperPaneLayout.setHorizontalGroup(
            jupperPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jupperPaneLayout.createSequentialGroup()
                .addContainerGap(449, Short.MAX_VALUE)
                .addComponent(jcopyIBAN, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152))
            .addGroup(jupperPaneLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jupperPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jupperPaneLayout.createSequentialGroup()
                        .addGroup(jupperPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jupperPaneLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jfullName, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jupperPaneLayout.createSequentialGroup()
                                .addComponent(jbalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jIBAN)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jupperPaneLayout.createSequentialGroup()
                        .addComponent(jdeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jwithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jupperPaneLayout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(jaccountType, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jupperPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
        );
        jupperPaneLayout.setVerticalGroup(
            jupperPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jupperPaneLayout.createSequentialGroup()
                .addGroup(jupperPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jupperPaneLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jupperPaneLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jaccountType, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jfullName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jupperPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jIBAN)
                            .addComponent(jbalance, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcopyIBAN)))
                .addGap(12, 12, 12)
                .addGroup(jupperPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jdeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jwithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(274, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jupperPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jupperPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jcopyIBANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcopyIBANActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcopyIBANActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jIBAN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jaccountType;
    private javax.swing.JLabel jbalance;
    private javax.swing.JButton jcopyIBAN;
    private javax.swing.JButton jdeposit;
    private javax.swing.JLabel jfullName;
    private javax.swing.JPanel jupperPane;
    private javax.swing.JButton jwithdraw;
    // End of variables declaration//GEN-END:variables
}
